version: '3'
services:
  backend:
    image: jejo1/tessera-backend-dev
    environment:
      - PORT

      - MONGODB_URI
      - EMAIL_HOST
      - EMAIL_PORT
      - EMAIL_USER

      - EMAIL_PASS

      - SECRETJWT

      - GMAIL_USERNAME
      - GMAIL_PASSWORD
      - OAUTH_CLIENT_ID

      - FACEBOOK_CLIENT_ID
      - FACEBOOK_CLIENT_SECRET

      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET

      - AUTH_EMAIL

      - EMAIL_TEST_APP_PSWD

      - dbUrl
      
      - SECRET

      - OAUTH_CLIENT_SECRET
      - OAUTH_REFRESH_TOKEN
      - OAUTH_ACCESS_TOKEN
    ports:
      - "3000:3000"
  nginx:
    image: jejo1/tessera-nginx-dev
    depends_on:
      - backend
    ports:
      - "80:80"