version: '3'
services:
  backend:
    image: jejo1/tessera-backend-dev
    environment:
      - BASE_URL
      - PORT

      - MONGODB_URI
      - EMAIL_HOST
      - EMAIL_PORT
      - EMAIL_USER
      - EMAIL_PASS

      - SECRETJWT

      - FACEBOOK_CLIENT_ID
      - FACEBOOK_CLIENT_SECRET

      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
    ports:
      - "3000:3000"
    restart: always
  nginx:
    image: jejo1/tessera-nginx-dev
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: always
